### ISSUE TITLE
how to close the GoTest floatterm windows

### ISSUE THREAD

**Issue by jaredmcqueen** [ray-x/go.nvim#82]
How do I close the floating floatterm after I run `GoTest` ?
Right now I have to run this long lua script.  There has to be a faster way to switch to the terminal and exit it.

```lua
lua for _, win in ipairs(vim.api.nvim_list_wins()) do local config = vim.api.nvim_win_get_config(win); if config.relative ~= "" then vi
m.api.nvim_win_close(win, false); print('Closing window', win) end end
```

**Comment by jaredmcqueen** [comment]
Ok, kind of figured it out:
 `C-w-o`

**Comment by jaredmcqueen** [comment]
Sorry, re-opening because as it turns out, `Control-w o` closes all windows but the current one.  That's not really what I want

**Comment by ray-x** [comment]
You can do `:q` as you quit other vim sessions.

**Comment by prurph** [comment]
Is `require ('go.term').close()` supposed to close this window? I've found it only works if the terminal is focused. It would be great if there were a good way to do this since the window is not focused by default when running `:GoTest`.

**Comment by ray-x** [comment]
\<c-e> ?

**Comment by jaredmcqueen** [comment]
thanks all, I'm all set.

**Comment by prurph** [comment]
> \<c-e> ?

I use the first script or <C-w> o etc to close it. I was wondering if the close function in term.lua was intended to close the floating window when it isn't focused because it does not seem to do that. It would be nice if there were a function users could bind that would close the go.nvim floating window and only that window, regardless of whether it is currently focused or not.

AFAICT though it's not trivial to determine which floating window was created by go.nvim without keeping track of window ids though so it might not be worth adding that functionality.

**Comment by ray-x** [comment]
Cool, I think I know what is the issue. The closer setup was set to float terminal instead of the current buffer. So you need to focus on the floating windows to close it.
I change the code so the setup is stored in the current buffer.  And you can re-map the `require('go.term').close()` to current buffer (or globally) to close the terminal.
